### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kuviman** [kuviman/nixfiles#7]
- [x] https://github.com/folke/trouble.nvim
- [ ] https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/
- [x] https://github.com/Eandrju/cellular-automaton.nvim
- [ ] lazygit copy?
